In [1]:
import pandas as pd

In [2]:
# Dataframe
info = {
    "Name" : ["Rahul", "Vijay", "kavya"],
    "CGPA" : [9.4, 8.3, 9.0]
}

df = pd.DataFrame(info)

print(df)

    Name  CGPA
0  Rahul   9.4
1  Vijay   8.3
2  kavya   9.0

In [3]:
df

    Name  CGPA
0  Rahul   9.4
1  Vijay   8.3
2  kavya   9.0

### Series in Pandas

In [4]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

#index 
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

In [5]:
# label
s = pd.Series([23, 24, 25, 26], index = ["Adam", "Eve", "Bob", "charlie"])
print(s)

print(s["Adam"])
print(s["Bob"])
print(s.index)

Adam       23
Eve        24
Bob        25
charlie    26
dtype: int64
23
25
Index(['Adam', 'Eve', 'Bob', 'charlie'], dtype='object')

In [6]:
# Series Properties
s = pd.Series([23, 24, "abc"], index = ["Adam", "Eve", 25])  # Homogeneous 
print(s)

# -> Vectorized Operations
s1 = pd.Series([1, 2, 3, 4, 5])       
s2 = pd.Series([10, 20, 30, 40, 50])
print(s1 + s2)     

s1[0] = 100
print(s1)
changed_s1 = s1.drop(0)
print(changed_s1)

Adam     23
Eve      24
25      abc
dtype: object
0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
# DataFrame

info = {
    "Name" : ["Adam", "Bob", "Eve"],
    "Age" : [23, 24, 25],
    "GPA" : [9.5, 8.6, 7.3]
}

df = pd.DataFrame(info)

print(df, type(df))

print(df.index)
print(df.columns)

   Name  Age  GPA
0  Adam   23  9.5
1   Bob   24  8.6
2   Eve   25  7.3 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [8]:
# list by DataFrame
df = pd.DataFrame([["Adam", 23], ["Bob", 24], ["Eve", 23]], columns = ["Name", "Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   23

In [9]:
# numpy by DataFrame
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])

df = pd.DataFrame(np_arr, columns = ["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [10]:
# csv data
df = pd.read_csv("offers-1000.csv")
print(df, type(df))

     index            ean  stock  price
0        1  2010743556564    669    135
1        2  2668829157992    476    584
2        3   429683856399    875     44
3        4  2548029150224     77    251
4        5  3442300385932    742    737
..     ...            ...    ...    ...
995    996  6028936916060    265    955
996    997  2115761782459    318    517
997    998    20345729398    963    600
998    999  7572833987849    719    792
999   1000  6410234214823    417    340

[1000 rows x 4 columns] <class 'pandas.core.frame.DataFrame'>

### DataFrame methods

In [11]:
df.head() # starting 5 rows

   index            ean  stock  price
0      1  2010743556564    669    135
1      2  2668829157992    476    584
2      3   429683856399    875     44
3      4  2548029150224     77    251
4      5  3442300385932    742    737

In [12]:
df.tail() # last 5 rows

     index            ean  stock  price
995    996  6028936916060    265    955
996    997  2115761782459    318    517
997    998    20345729398    963    600
998    999  7572833987849    719    792
999   1000  6410234214823    417    340

In [13]:
df.sample(4) # random value

     index            ean  stock  price
349    350  8494110591718    113    366
867    868  9760653072922     41    401
67      68  2702688489334    184     83
397    398  9721628848744    765    527

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   1000 non-null   int64
 1   ean     1000 non-null   int64
 2   stock   1000 non-null   int64
 3   price   1000 non-null   int64
dtypes: int64(4)
memory usage: 31.4 KB

In [15]:
df.shape # tuple value

(1000, 4)

In [16]:
df.describe() # only for numerical value

             index           ean        stock        price
count  1000.000000  1.000000e+03  1000.000000  1000.000000
mean    500.500000  4.963619e+12   500.277000   503.552000
std     288.819436  2.835047e+12   292.692137   286.320675
min       1.000000  2.034573e+10     1.000000     3.000000
25%     250.750000  2.471468e+12   235.250000   262.750000
50%     500.500000  4.990741e+12   496.000000   511.500000
75%     750.250000  7.443589e+12   761.250000   737.000000
max    1000.000000  9.970325e+12   999.000000   998.000000

In [17]:
df.columns

Index(['index', 'ean', 'stock', 'price'], dtype='object')

In [18]:
df.nunique()  # unique value

index    1000
ean       990
stock     639
price     645
dtype: int64