In [1]:
import pandas as pd

In [2]:
# Dataframe
info = {
    "Name" : ["Rahul", "Vijay", "kavya"],
    "CGPA" : [9.4, 8.3, 9.0]
}

df = pd.DataFrame(info)

print(df)

    Name  CGPA
0  Rahul   9.4
1  Vijay   8.3
2  kavya   9.0

In [3]:
df

    Name  CGPA
0  Rahul   9.4
1  Vijay   8.3
2  kavya   9.0

### Series in Pandas

In [4]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

#index 
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

In [5]:
# label
s = pd.Series([23, 24, 25, 26], index = ["Adam", "Eve", "Bob", "charlie"])
print(s)

print(s["Adam"])
print(s["Bob"])
print(s.index)

Adam       23
Eve        24
Bob        25
charlie    26
dtype: int64
23
25
Index(['Adam', 'Eve', 'Bob', 'charlie'], dtype='object')

In [6]:
# Series Properties
s = pd.Series([23, 24, "abc"], index = ["Adam", "Eve", 25])  # Homogeneous 
print(s)

# -> Vectorized Operations
s1 = pd.Series([1, 2, 3, 4, 5])       
s2 = pd.Series([10, 20, 30, 40, 50])
print(s1 + s2)     

s1[0] = 100
print(s1)
changed_s1 = s1.drop(0)
print(changed_s1)

Adam     23
Eve      24
25      abc
dtype: object
0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

## DataFrame

In [7]:
# DataFrame

info = {
    "Name" : ["Adam", "Bob", "Eve"],
    "Age" : [23, 24, 25],
    "GPA" : [9.5, 8.6, 7.3]
}

df = pd.DataFrame(info)

print(df, type(df))

print(df.index)
print(df.columns)

   Name  Age  GPA
0  Adam   23  9.5
1   Bob   24  8.6
2   Eve   25  7.3 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [8]:
# list by DataFrame
df = pd.DataFrame([["Adam", 23], ["Bob", 24], ["Eve", 23]], columns = ["Name", "Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   23

In [9]:
# numpy by DataFrame
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])

df = pd.DataFrame(np_arr, columns = ["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [10]:
# csv data
df = pd.read_csv("offers-1000.csv")
print(df, type(df))

     index            ean  stock  price
0        1  2010743556564    669    135
1        2  2668829157992    476    584
2        3   429683856399    875     44
3        4  2548029150224     77    251
4        5  3442300385932    742    737
..     ...            ...    ...    ...
995    996  6028936916060    265    955
996    997  2115761782459    318    517
997    998    20345729398    963    600
998    999  7572833987849    719    792
999   1000  6410234214823    417    340

[1000 rows x 4 columns] <class 'pandas.core.frame.DataFrame'>

### DataFrame methods

In [11]:
df.head() # starting 5 rows

   index            ean  stock  price
0      1  2010743556564    669    135
1      2  2668829157992    476    584
2      3   429683856399    875     44
3      4  2548029150224     77    251
4      5  3442300385932    742    737

In [12]:
df.tail() # last 5 rows

     index            ean  stock  price
995    996  6028936916060    265    955
996    997  2115761782459    318    517
997    998    20345729398    963    600
998    999  7572833987849    719    792
999   1000  6410234214823    417    340

In [13]:
df.sample(4) # random value

     index            ean  stock  price
357    358  5915594059851    421    669
1        2  2668829157992    476    584
91      92  3394264333583    438    355
362    363  8465400688845    280    220

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   1000 non-null   int64
 1   ean     1000 non-null   int64
 2   stock   1000 non-null   int64
 3   price   1000 non-null   int64
dtypes: int64(4)
memory usage: 31.4 KB

In [15]:
df.shape # tuple value

(1000, 4)

In [16]:
df.describe() # only for numerical value

             index           ean        stock        price
count  1000.000000  1.000000e+03  1000.000000  1000.000000
mean    500.500000  4.963619e+12   500.277000   503.552000
std     288.819436  2.835047e+12   292.692137   286.320675
min       1.000000  2.034573e+10     1.000000     3.000000
25%     250.750000  2.471468e+12   235.250000   262.750000
50%     500.500000  4.990741e+12   496.000000   511.500000
75%     750.250000  7.443589e+12   761.250000   737.000000
max    1000.000000  9.970325e+12   999.000000   998.000000

In [17]:
df.columns

Index(['index', 'ean', 'stock', 'price'], dtype='object')

In [18]:
df.nunique()  # unique value

index    1000
ean       990
stock     639
price     645
dtype: int64

## Practice Kaggle AQI Data set

In [19]:
# AQI Data Set
df = pd.read_csv("globalAirQuality.csv")
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [20]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

### Selecting data

In [21]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [22]:
# selcect columns
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [23]:
# Select rows (label & Index based) - loc & iloc

df.loc[2] # row
df.loc[0:2] # start idx : end idx (inclusive)

df.iloc[2] # row same as loc[2]
df.iloc[0:2] # start idx : end idx (exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

#### Select rows & columns

In [63]:
df.loc[0, "aqi"]

np.int64(108)

In [55]:
df.loc[0, ["city", "aqi"]]

city    New York
aqi          108
Name: 0, dtype: object

In [56]:
df.loc[0:2, ["city", "aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84

In [59]:
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [57]:
df.iloc[0:3, 2]  # iloc only take numreric value for 2 is index of city

0    New York
1    New York
2    New York
Name: city, dtype: object

In [60]:
df.loc[0:2, ["country", "city", "latitude", "longitude"]]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [61]:
df.iloc[0:3, 1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [25]:
# Select single scalar value - at & iat
df.at[0, "city"]
df.iat[0, 2]

'New York'

In [26]:
# copy vs view
cities = df["city"].copy()  # we can't change our original dataset that's we use .copy() funcition.
cities[0] = "Mumbai" #copy, then changing  happens in copy dataset not in original dataset. 

cities

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [27]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

### Filtering Data

In [28]:
# Filtering of Data

df[ df["aqi"] > 100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [30]:
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]
df[ (df["aqi"] > 100) & (df["temperature"] < 30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
12,2025-11-05 06:25:17.554219,US,New York,40.713,-74.006,57.227,28.916,30.698,8.091,63.108,0.967,114,14.584,46.654,5.570
13,2025-11-05 07:25:17.554219,US,New York,40.713,-74.006,26.147,58.714,49.826,5.228,51.651,0.615,124,27.299,76.014,0.786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17988,2025-11-19 06:25:17.554219,CH,Zurich,47.377,8.542,61.305,97.044,23.317,6.793,57.102,1.022,122,13.982,30.822,6.769
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [39]:
df[ df["aqi"] > 100][["city", "aqi"]] #chaiend operation

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]

In [40]:
df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]] #chaiend operation

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [46]:
aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]
aqi_data
aqi_data.iloc[0]

# aqi_dat.loc[0] #give error
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

### Query

In [49]:
# Query
df.query("aqi > 100")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [53]:
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [54]:
aqi_val = 100
df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]